name: H-EasterEggs
version: '${project.version}'
main: fr.herllox.heastereggs.HEasterEggs
api-version: 1.18
authors: [ Herllox ]
description: EasterEggs plugin made by Herllox.
commands:
  easteregg:
    aliases:
      - eegg
      - eastereggs
